method: nonlinearmm
data:
  # path_shapes: /home/vikas/Documents/data/ctx_non_linear_data_neutral_only #ctx_non_linear_data
  path_shapes: /home/vikas/Documents/.ctx_non_linear_data_neutral_only
  disp_size: 20339
  b_size: 1 #37
  with_shuffle: True
training:
  # out_dir: '/home/vikas/Documents/nl3dmm_checkpoints/disney_L1_KLD_geomMM_v2_neutral_captured_version3.0/'
  out_dir: '/scratch/vikas/temp/.ctx_out/disney_L1_KLD_geomMM_v2_neutral/'
  batch_size: 64
  model_selection_metric: null # add loss term if needed
  model_selection_mode: maximize # or minimize?
  print_every: 500
  visualize_every: 0
  checkpoint_every: 5000
  validate_every: 5000
  backup_every: 5000
  moving_average_beta: 0
  weight_vaeloss: 1.
  weight_geom_l1loss: 1000
  weight_albedo_l1loss: 0
  weight_kldloss: 0.01
  experiment: 'generative'
  gradient_penalties_reg: 0.
  lr: 0.0005
  multi_gpu: false
model:
  main_network: version_2
  decoder: geom_resnet # {geom, joint, geom_albedo}
  id_vae_encoder: id_resnet
  exp_vae_encoder: exp_resnet
  decoder_kwargs:
    leaky: True
  vae_encoder_kwargs:
    leaky: True
  n_id: 32
  n_exp: 32 # 11, 32, 256
  model_url:
generation:
  batch_size: 213
  # batch_size: 2
  # batch_size: 49
test:
  model_file: model_60000.pt
  vis_dir: 'out/disney_L1_KLD_geomMM_v2_neutral_captured_latent_viz_interpolate_60k'
  dataset_split: 'test_vis'
  interpol: False
  # generation_mode: 'test_vae'
  #generation_mode: 'interpolate'
  # generation_mode: 'eval_vae'
  # generation_mode: 'sample_vae'
  #generation_mode: 'iter_sample_vae'
  # generation_mode: tsne_viz
  generation_mode: latent_viz_interpolate
